pytorch可以更好地将反向传播进行求导

In [50]:
import torch


需要求导可以手动定义

In [51]:
x=torch.randn(3,4,requires_grad=True)
x

tensor([[ 0.1633,  0.6406,  2.7759, -0.5128],
        [ 0.6696, -0.2626,  0.4898,  0.8851],
        [ 0.4948,  1.0772,  0.3865,  1.5520]], requires_grad=True)

In [52]:
## 或者使用pytorch定义
x.requires_grad=True
x

tensor([[ 0.1633,  0.6406,  2.7759, -0.5128],
        [ 0.6696, -0.2626,  0.4898,  0.8851],
        [ 0.4948,  1.0772,  0.3865,  1.5520]], requires_grad=True)

In [53]:
b=torch.randn(3,4,requires_grad=True)
t=x+b
y=t.sum()
y

tensor(13.8744, grad_fn=<SumBackward0>)

In [54]:
y.backward() # 反向传播
b.grad # 求导


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 神经网络的求偏导过程:
![image](./assets/1.png)

In [ ]:
# 计算流程
x=torch.randn(1)
b=torch.randn(1,requires_grad=True)
w=torch.randn(1,requires_grad=True)
y=w*x
z=y+b
x.requires_grad,b.requires_grad,w.requires_grad,y.requires_grad # y也需要, 因为w是在y的后面计算w必须先计算y

In [56]:
x.is_leaf,b.is_leaf,w.is_leaf,y.is_leaf,z.is_leaf # leaf节点, 是不是最后一个计算偏导的节点

(True, True, True, False, False)

In [57]:
z.backward(retain_graph=True) # 如果不对梯度进行清零的话, 梯度默认会累加起来
w.grad

tensor([-0.5919])

In [58]:
b.grad

tensor([1.])